### ISSUE TITLE
`git clone --recurse-submodules --recursive` fails to checkout `doc`

### ISSUE THREAD

**Issue by worduk** [B2R2-org/B2R2#51] opened 2024-08-30 16:34 UTC
**Describe the bug**
`git clone --recurse-submodules --recursive` fails to checkout `doc`

**To Reproduce**
1. `git clone --recurse-submodules --recursive https://github.com/B2R2-org/B2R2` 

**Expected behavior**
Full clone of repository

**Comment by sangkilc** [comment] 2024-08-30 21:28
Could you share the output? I cannot reproduce this problem, and this seems to be your `git` problem, not B2R2's problem.

**Comment by worduk** [comment] 2024-09-03 08:51
```sh
git clone --recurse-submodules --recursive http://github.com/B2R2-org/B2R2
Cloning into 'B2R2'...
warning: redirecting to https://github.com/B2R2-org/B2R2/
remote: Enumerating objects: 17351, done.
remote: Counting objects: 100% (7622/7622), done.
remote: Compressing objects: 100% (2048/2048), done.
remote: Total 17351 (delta 6067), reused 6946 (delta 5567), pack-reused 9729 (from 1)
Receiving objects: 100% (17351/17351), 9.72 MiB | 8.49 MiB/s, done.
Resolving deltas: 100% (13719/13719), done.
Submodule 'docs' (git@github.com:B2R2-org/APIDoc.git) registered for path 'docs'
Cloning into '/usr/src/reverse_engineering/B2R2-org/B2R2/docs'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:B2R2-org/APIDoc.git' into submodule path '/usr/src/reverse_engineering/B2R2-org/B2R2/docs' failed
Failed to clone 'docs'. Retry scheduled
Cloning into '/usr/src/reverse_engineering/B2R2-org/B2R2/docs'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:B2R2-org/APIDoc.git' into submodule path '/usr/src/reverse_engineering/B2R2-org/B2R2/docs' failed
Failed to clone 'docs' a second time, aborting
```

**Comment by sangkilc** [comment] 2024-09-03 12:32
It is because you don't have the right SSH key setup for cloning this repository: https://github.com/B2R2-org/APIDoc

You can simply ignore cloning APIDoc because it is nothing to do with building the project. If you really want to fully clone all the submodules, then you should set up your SSH key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

I'm closing this issue as this is a git configuration problem.

**Closed by sangkilc** 2024-09-03 12:32 UTC
Labels: question
